import shin_ramen from "../img/shin_ramen.png";
export const specialMenu = [
  {
    id: 1,
    name: "Chasu Ramen",
    category: "Ramen",
    price: "$49.99",
    dis: "$29.99",
    img: shin_ramen,
    rating: 4.5,
  },
  {
    id: 1,
    name: "Chasu Ramen",
    category: "Ramen",
    price: "$49.99",
    dis: "$29.99",
    img: shin_ramen,
    rating: 4.5,
  },
  {
    id: 1,
    name: "Chasu Ramen",
    category: "Ramen",
    price: "$49.99",
    dis: "$29.99",
    img: shin_ramen,
    rating: 4.5,
  },
  {
    id: 1,
    name: "Chasu Ramen",
    category: "Ramen",
    price: "$49.99",
    dis: "$29.99",
    img: shin_ramen,
    rating: 4.5,
  },
  {
    id: 1,
    name: "Chasu Ramen",
    category: "Ramen",
    price: "$49.99",
    dis: "$29.99",
    img: shin_ramen,
    rating: 4.5,
  },
  {
    id: 1,
    name: "Chasu Ramen",
    category: "Ramen",
    price: "$49.99",
    dis: "$29.99",
    img: shin_ramen,
    rating: 4.5,
  },
];
